#for getting all the post
GET http://localhost:3000/api/v1/post/id/6425c95e3e6777679e94fd99/ HTTP/1.1

###
#for adding a post
POST http://localhost:3000/api/v1/post/ HTTP/1.1
Content-Type: application/json

{
"post":
{
  "userId": "ob7iturhxvcvbnm",
  "title": "just a title",
  "content": "just a content",
  "image": [
    {
      "url": "www.google.com",
      "name": "image1"
    }
  ],
  "votes": {
    "upvote": ["tr5tgyuhfdrse4556","54567utyghj"],
    "downvote": ["oiuhgffvghjk","98765rdfghnbvc"]
  },
  "date": "2023-3-30",
  "answers": ["uytdtfghjn","dxcvbnm98765"],
  "subject": "Chemistry"
    }
}

###
#for deleting a post
DELETE http://localhost:3000/api/v1/post/6425c95e3e6777679e94fd99/ HTTP/1.1

###
#for testing the post
GET http://localhost:3000/api/v1/post/subject/Chemistry/ HTTP/1.1