# for getting all the users
GET http://localhost:3000/api/v1/user/6421d67862ec84a3789d9e58/ HTTP/1.1

###
#for adding a user
POST http://localhost:3000/api/v1/user/ HTTP/1.1
Content-Type: application/json

{
    "user":{
        "token":"1223jois",
        "name":"Mr.M",
        "school":"KMGSS"
    }
}

###
#for deleting one user
DELETE http://localhost:3000/api/v1/user/6421d67862ec84a3789d9e58/ HTTP/1.1